#!/bin/bash
#---------------------------------------------------------
# written by: Lawrence McDaniel
#             https://lawrencemcdaniel.com
#
# date:       aug-2022
#
# usage:      create mysql database and user account
#--------------------------------------------------------

echo "Initialising MySQL..."
mysql_connection_max_attempts=10
mysql_connection_attempt=0
until mysql -u {{ MYSQL_ROOT_USERNAME }} --password="{{ MYSQL_ROOT_PASSWORD }}" --host "{{ MYSQL_HOST }}" --port {{ MYSQL_PORT }} -e 'exit'
do
    mysql_connection_attempt=$(expr $mysql_connection_attempt + 1)
    echo "    [$mysql_connection_attempt/$mysql_connection_max_attempts] Waiting for MySQL service (this may take a while)..."
    if [ $mysql_connection_attempt -eq $mysql_connection_max_attempts ]
    then
      echo "MySQL initialisation error" 1>&2
      exit 1
    fi
    sleep 10
done
echo "MySQL is up and running"



# create the license manager database
echo "create license_manager database"
mysql -u {{ MYSQL_ROOT_USERNAME }} --password="{{ MYSQL_ROOT_PASSWORD }}" --host "{{ MYSQL_HOST }}" --port {{ MYSQL_PORT }} -e "CREATE DATABASE IF NOT EXISTS {{ LICENSE_MANAGER_MYSQL_DATABASE }};"

# create a mysql user w permissions
echo "create license_manager user"
mysql -u {{ MYSQL_ROOT_USERNAME }} --password="{{ MYSQL_ROOT_PASSWORD }}" --host "{{ MYSQL_HOST }}" --port {{ MYSQL_PORT }} -e "CREATE USER IF NOT EXISTS '{{ LICENSE_MANAGER_MYSQL_USERNAME }}';"
mysql -u {{ MYSQL_ROOT_USERNAME }} --password="{{ MYSQL_ROOT_PASSWORD }}" --host "{{ MYSQL_HOST }}" --port {{ MYSQL_PORT }} -e "ALTER USER '{{ LICENSE_MANAGER_MYSQL_USERNAME }}'@'%' IDENTIFIED BY '{{ LICENSE_MANAGER_MYSQL_PASSWORD }}';"
mysql -u {{ MYSQL_ROOT_USERNAME }} --password="{{ MYSQL_ROOT_PASSWORD }}" --host "{{ MYSQL_HOST }}" --port {{ MYSQL_PORT }} -e "GRANT ALL ON {{ LICENSE_MANAGER_MYSQL_DATABASE }}.* TO '{{ LICENSE_MANAGER_MYSQL_USERNAME }}'@'%';"

# mcdaniel aug-2022
# not sure how necessary this really is, but just to be on the safe side we're
# syncing the License Manager user list to that of the LMS.
echo "sync license_manager.core_user to openedx.auth_user"
mysql -u {{ MYSQL_ROOT_USERNAME }} --password="{{ MYSQL_ROOT_PASSWORD }}" --host "{{ MYSQL_HOST }}" --port {{ MYSQL_PORT }} -e "\
INSERT license_manager.core_user (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, full_name, lms_user_id) \
     SELECT     lms_user.password, \
               lms_user.last_login, \
               lms_user.is_superuser, \
               lms_user.username, \
               lms_user.first_name, \
               lms_user.last_name, \
               lms_user.email, \
               lms_user.is_staff, \
               lms_user.is_active, \
               lms_user.date_joined, \
               CASE WHEN NOT ISNULL(lms_profile.name) THEN lms_profile.name ELSE lms_user.first_name + ' ' + lms_user.last_name END as full_name, \
               lms_user.id as lms_user_id \
     FROM     openedx.auth_user lms_user \
               LEFT JOIN openedx.auth_userprofile as lms_profile ON (lms_user.id = lms_profile.user_id) \
               LEFT JOIN license_manager.core_user credentials_user ON (lms_user.id = credentials_user.lms_user_id) \
               LEFT JOIN license_manager.core_user credentials_user2 ON (lms_user.username = credentials_user2.username) \
     WHERE     (credentials_user.id IS NULL) AND \
               (credentials_user2.username IS NULL);"
