#!/bin/bash
#------------------------------------------------------------------------------
# written by: Lawrence McDaniel
#             https://lawrencemcdaniel.com
#
# date:       aug-2022
#
# usage:      run database migrations once mysql is up and running.
#------------------------------------------------------------------------------

echo "license_manager service - ./manage.py migrate"

dockerize -wait tcp://{{ MYSQL_HOST }}:{{ MYSQL_PORT }} -timeout 20s

echo "Loading settings $DJANGO_SETTINGS_MODULE"

./manage.py migrate --noinput

# mcdaniel aug-2022
# not sure how necessary this really is, but just to be on the safe side we're
# syncing the License Manager user list to that of the LMS.
# echo "sync license_manager.core_user to openedx.auth_user"
# mysql -u {{ MYSQL_ROOT_USERNAME }} --password="{{ MYSQL_ROOT_PASSWORD }}" --host "{{ MYSQL_HOST }}" --port {{ MYSQL_PORT }} -e "\
# INSERT license_manager.core_user (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, full_name, lms_user_id) \
#      SELECT     lms_user.password, \
#                lms_user.last_login, \
#                lms_user.is_superuser, \
#                lms_user.username, \
#                lms_user.first_name, \
#                lms_user.last_name, \
#                lms_user.email, \
#                lms_user.is_staff, \
#                lms_user.is_active, \
#                lms_user.date_joined, \
#                CASE WHEN NOT ISNULL(lms_profile.name) THEN lms_profile.name ELSE lms_user.first_name + ' ' + lms_user.last_name END as full_name, \
#                lms_user.id as lms_user_id \
#      FROM     openedx.auth_user lms_user \
#                LEFT JOIN openedx.auth_userprofile as lms_profile ON (lms_user.id = lms_profile.user_id) \
#                LEFT JOIN license_manager.core_user credentials_user ON (lms_user.id = credentials_user.lms_user_id) \
#                LEFT JOIN license_manager.core_user credentials_user2 ON (lms_user.username = credentials_user2.username) \
#      WHERE     (credentials_user.id IS NULL) AND \
#                (credentials_user2.username IS NULL);"
